#!/bin/bash

#Muestra los routers encendidos y su tipo



#kill `ps -ef|grep "[i]86bi_linux-adventerprisek9_xsi-ms.*"|awk '{print $2}'`


ps -ef|grep "[i]86bi_linux-adventerprisek9_xsi-ms.*"|awk '{print $NF}'>/tmp/iol_routers

rm -f /tmp/iou_active
cat /tmp/iol_routers | while read LINE
do
	echo $LINE ": $(tput setaf 1)linux 15.3$(tput sgr0)">>/tmp/iou_active
done


ps -ef|grep "[w]rapper-linux.*linux-l3.*"|awk '{print $NF}' >/tmp/iou_routers
cat /tmp/iou_routers | while read LINE
do
	echo $LINE ": $(tput setaf 2)IOU router "`ps -ef|grep "[w]rapper-linux.*linux-l3.* $LINE$"|awk '{print $10}'|cut -d'-' -f5|sed 's/.bin//g'` "$(tput sgr0)">>/tmp/iou_active
done

ps -ef|grep "[w]rapper-linux.*tpgen.*"|awk '{print $NF}' >/tmp/iou_routers
cat /tmp/iou_routers | while read LINE
do
	echo $LINE ": $(tput setaf 3)IOU PAGENT 12.4(20)$(tput sgr0)">>/tmp/iou_active
done

ps -ef|grep "[w]rapper-linux.*linux-l2.*"|awk '{print $NF}' >/tmp/iou_routers
cat /tmp/iou_routers | while read LINE
do
	echo $LINE ": $(tput setaf 4)IOU switch "`ps -ef|grep "[w]rapper-linux.*linux-l2.*"|awk '{print $10}'|cut -d'-' -f5|sed 's/.bin//g'`>>/tmp/iou_active
done


if [ -f  /tmp/iou_active ];
then
	cat /tmp/iou_active | sort -n 
else
	echo "$(tput setaf 1)$(tput bold)There are no routers currently running"
fi
echo "$(tput sgr0)"

