#!/bin/bash







function banner (){
	echo "Usage: iou_connect <router>:iface <tap> [<ip address>/<mask>]"
	echo
	echo "Device type:"
	echo "	-r : iou router"
	echo "	-s : l2iou switch"
	echo "	-p : iou pagent"
	echo "	-l : iol router"
	echo 
	echo "	OPTIONS"
	echo "	-id : identifier of the router to be started"
	echo "		-[rsp]: <router_id> [console port]"
	echo "		-l: <router_id> [<configuration_file>"
	echo "	-range : several routers to be started at once"
	echo "		-[rsp]: <number of routers> [<origin_router> [<origin_console>]]"
	echo "		-l: [-c] <number of routers> [<origin_router> [<origin_console>]]"
}

#Returns value of the tap router
#if the tap is not in the range 800-899 returns an error
#if the link does not exis returns an error
function gettap_router()
{
	local tap_router=`grep " $1" NETMAP|cut -d' ' -f 1|cut -d':' -f 1`

	if [[ "$tap_router" == "" ]]
	then
		echo "1"
		return 1
	fi	
	if [[ "$tap_router" != 8[0-9][0-9] ]]
	then
		echo "2"
		return 2
	fi
	echo $tap_router
}	




#test whether NETMAP file exist or not
if [ ! -f NETMAP ];
then
	echo "NETMAP does not exist"
	exit
fi




#Exit if the number of parameters is different from 1 or 2
if [ $# != 2 ] && [ $# != 3 ];
then
    banner
	exit
fi

#check NETMAP 
router=`gettap_router $1`
if [[ $router == 1 ]];
then
	echo "Error: link $1 does not exist"
	exit
elif [[ $sniffer == 2 ]];
then
	echo "Error: there is no router defined in 800-899 range"
	exit
fi

#check tap interface
tap_interface=`ip link | grep $2`
if [[ $tap_interface == "" ]];
then
    echo "Interface $2 does not exist. Creating tap interface"
    if [ $# == 2 ];
    then
        ioltuncfg --create --int=$2 --up
    else
        ioltuncfg --create --int=$2 --add=$3 --up
    fi
else
    echo "Interface $2 exists"
fi

iou2net.pl -t $2 -p $router &












